Disable mob spawn on the chisel blocks
GTNewHorizons/Chisel pull request #26
Opened 2023-01-28 21:17 UTC by Zereff06

All gt blocks have anti-spawn protection, why don't the decorative blocks? I think it would be okay if mobs were not spawned on the base, but only outside of it. Forever watching the lights on the base or the mechanisms forbidding spawn is tiresome. I think it would be great if the base will not be mobs at all, because where do they come from?

2023-01-28 21:20 UTC, Dream-Master commented
?

2023-01-29 00:13 UTC, Zereff06 commented
@Dream-Master now it's done.

2023-01-29 08:25 UTC, tyrael93 commented
Yeah no
I think this is big enough to warrant more than just a "nope, it's done"

2023-01-29 17:56 UTC, mitchej123 requested changes
Needs to be a (cached) config option.  I don't think globally disabling it without an option is the way to go.

2023-01-29 17:56 UTC, mitchej123 commented on src/main/java/team/chisel/block/BlockCarvable.java
> +        return false;
This should be a config.

2023-01-31 18:16 UTC, OneEyeMaker approved these changes

2023-01-31 18:24 UTC, mitchej123 approved these changes

2023-01-31 18:24 UTC, merged